### ISSUE TITLE
Настройка Интеркассы

### ISSUE THREAD

**Issue by jubi468** [0xdenys/interkassa#2]
Привет, большое спасибо за плагин, он работает! =) Но не могу разобраться что писать в настройках Интерфейс, самой Интеркассы...Сейчас при проведении платежа он как бы проходит, но при этом в интеркассе ошибка 

https://monosnap.com/file/C46oyZASKZVX6NOrGRE2PwClvFL5bL

настройки интерфейса:

https://monosnap.com/file/q6g7h5TjjnA7R8HzT1dme9oEi6SMMK

Заранее спасибо за помощь =)

**Comment by VictorSlate** [comment]
Присоединяюсь к вопросу. Оплата проходит, от Интеркассы приходит письмо, но в Woocommerce статус заказа так и остается "в ожидании оплаты".

**Comment by VictorSlate** [comment]
@jubi468 Вам удалось решить проблему? Если да, подскажите пожалуйста как?

**Comment by cheresier** [comment]
@VictorSlate, а Вам удалось решить проблему? Тоже с ней бьюсь.

**Comment by 0xdenys** [comment]
done
